site_name: "Hopsworks Documentation"
site_description: "Official documentation for Hopsworks and its Feature Store - an open source data-intensive AI platform used for the development and operation of machine learning models at scale."
site_author: "Hopsworks"
site_url: "https://docs.hopsworks.ai/"

# Repository
edit_uri: "https://github.com/logicalclocks/logicalclocks.github.io"
repo_url: "https://github.com/logicalclocks/hopsworks-api"
repo_name: logicalclocks/hopsworks-api

strict: false

nav:
  - Home: index.md
  - Getting Started ↗: https://colab.research.google.com/github/logicalclocks/hopsworks-tutorials/blob/master/quickstart.ipynb
  - Tutorials:
      - tutorials/index.md
  - Concepts:
      - Hopsworks Platform: concepts/hopsworks.md
      - MLOps Dictionary ↗: https://www.hopsworks.ai/mlops-dictionary?utm_source=web&utm_medium=docs
      - Feature Store:
          - Architecture: concepts/fs/index.md #hsfs
          - Feature Groups:
              - Overview: concepts/fs/feature_group/fg_overview.md
              - Write APIs: concepts/fs/feature_group/write_apis.md
              - Feature Pipelines: concepts/fs/feature_group/feature_pipelines.md
              - External Feature Groups: concepts/fs/feature_group/external_fg.md
              - Spine Group: concepts/fs/feature_group/spine_group.md
              - Data Validation/Stats/Alerts: concepts/fs/feature_group/fg_statistics.md
              - Feature Monitoring: concepts/fs/feature_group/feature_monitoring.md
              - Versioning: concepts/fs/feature_group/versioning.md
              - On-Demand Feature: concepts/fs/feature_group/on_demand_feature.md
          - Feature Views:
              - Overview: concepts/fs/feature_view/fv_overview.md
              - Offline API: concepts/fs/feature_view/offline_api.md
              - Online API: concepts/fs/feature_view/online_api.md
              - Consistent Transformations: concepts/fs/feature_view/training_inference_pipelines.md
              - Statistics: concepts/fs/feature_view/statistics.md
              - Feature Monitoring: concepts/fs/feature_view/feature_monitoring.md
              - Versioning: concepts/fs/feature_view/versioning.md
      - Projects:
          - Governance: concepts/projects/governance.md
          - Data Storage/Sharing: concepts/projects/storage.md
          - Tags/Search/Lineage: concepts/projects/search.md
          - CI/CD: concepts/projects/cicd.md
      - MLOps:
          - Prediction Services: concepts/mlops/prediction_services.md
          - Model Training: concepts/mlops/training.md
          - Model Registry: concepts/mlops/registry.md
          - Model Serving: concepts/mlops/serving.md
          - Vector Database: concepts/mlops/opensearch.md
          - BI Tools: concepts/mlops/bi_tools.md
          - Data Transformations: concepts/mlops/data_transformations.md
      - Development:
          - Outside Hopsworks: concepts/dev/outside.md # api-keys
          - Inside Hopsworks: concepts/dev/inside.md
  - Guides:
      - user_guides/index.md
      - Feature Store:
          - user_guides/fs/index.md
          - Data Source:
              - user_guides/fs/data_source/index.md
              - Configuration and Creation:
                  - JDBC: user_guides/fs/data_source/creation/jdbc.md
                  - Snowflake: user_guides/fs/data_source/creation/snowflake.md
                  - Kafka: user_guides/fs/data_source/creation/kafka.md
                  - HopsFS: user_guides/fs/data_source/creation/hopsfs.md
                  - S3: user_guides/fs/data_source/creation/s3.md
                  - Redshift: user_guides/fs/data_source/creation/redshift.md
                  - ADLS: user_guides/fs/data_source/creation/adls.md
                  - BigQuery: user_guides/fs/data_source/creation/bigquery.md
                  - GCS: user_guides/fs/data_source/creation/gcs.md
                  - RDS: user_guides/fs/data_source/creation/rds.md
              - Usage: user_guides/fs/data_source/usage.md
          - Feature Group:
              - user_guides/fs/feature_group/index.md
              - Create: user_guides/fs/feature_group/create.md
              - Create External: user_guides/fs/feature_group/create_external.md
              - Deprecate: user_guides/fs/feature_group/deprecation.md
              - Data Types and Schema management: user_guides/fs/feature_group/data_types.md
              - Statistics: user_guides/fs/feature_group/statistics.md
              - Data Validation:
                  - Getting started: user_guides/fs/feature_group/data_validation.md
                  - Advanced guide: user_guides/fs/feature_group/data_validation_advanced.md
                  - Best practices: user_guides/fs/feature_group/data_validation_best_practices.md
              - Feature Monitoring:
                  - Getting started: user_guides/fs/feature_group/feature_monitoring.md
                  - Advanced guide: user_guides/fs/feature_monitoring/feature_monitoring_advanced.md
              - Notification: user_guides/fs/feature_group/notification.md
              - On-Demand Transformations: user_guides/fs/feature_group/on_demand_transformations.md
              - Online Ingestion Observability: user_guides/fs/feature_group/online_ingestion_observability.md
          - Feature View:
              - user_guides/fs/feature_view/index.md
              - Overview: user_guides/fs/feature_view/overview.md
              - Training data: user_guides/fs/feature_view/training-data.md
              - Batch data: user_guides/fs/feature_view/batch-data.md
              - Feature vectors: user_guides/fs/feature_view/feature-vectors.md
              - Feature server: user_guides/fs/feature_view/feature-server.md
              - Query: user_guides/fs/feature_view/query.md
              - Helper Columns: user_guides/fs/feature_view/helper-columns.md
              - Model-Dependent Transformation Functions: user_guides/fs/feature_view/model-dependent-transformations.md
              - Spines: user_guides/fs/feature_view/spine-query.md
              - Feature Monitoring:
                  - Getting started: user_guides/fs/feature_view/feature_monitoring.md
                  - Advanced guide: user_guides/fs/feature_monitoring/feature_monitoring_advanced.md
              - Feature Logging: user_guides/fs/feature_view/feature_logging.md
          - Vector Similarity Search: user_guides/fs/vector_similarity_search.md
          - Transformation Functions: user_guides/fs/transformation_functions.md
          - Compute Engines: user_guides/fs/compute_engines.md
          - Client Integrations:
              - user_guides/integrations/index.md
              - Python / SageMaker / Kubeflow: user_guides/integrations/python.md
              - AWS EMR:
                  - Networking: user_guides/integrations/emr/networking.md
                  - Configure EMR for Hopsworks: user_guides/integrations/emr/emr_configuration.md
              - Azure HDInsight: user_guides/integrations/hdinsight.md
              - Azure Machine Learning:
                  - Designer: user_guides/integrations/mlstudio_designer.md
                  - Notebooks: user_guides/integrations/mlstudio_notebooks.md
              - Apache Spark: user_guides/integrations/spark.md
              - Apache Flink: user_guides/integrations/flink.md
              - Apache Beam: user_guides/integrations/beam.md
          - Sharing: user_guides/fs/sharing/sharing.md
          - Tags: user_guides/fs/tags/tags.md
          - Provenance: user_guides/fs/provenance/provenance.md
          - Feature Monitoring:
              - user_guides/fs/feature_monitoring/index.md
              - Scheduled Statistics: user_guides/fs/feature_monitoring/scheduled_statistics.md
              - Statistics Comparison: user_guides/fs/feature_monitoring/statistics_comparison.md
              - Interactive Graph: user_guides/fs/feature_monitoring/interactive_graph.md
      - Projects:
          - user_guides/projects/index.md
          - Authentication:
              - Registration: user_guides/projects/auth/registration.md
              - Login: user_guides/projects/auth/login.md
              - Password Recovery: user_guides/projects/auth/recovery.md
              - OAuth2 Authentication: user_guides/projects/auth/oauth.md
              - LDAP Authentication: user_guides/projects/auth/ldap.md
              - Kerberos Authentication: user_guides/projects/auth/krb.md
              - Update Profile: user_guides/projects/auth/profile.md
          - Projects:
              - Create Project: user_guides/projects/project/create_project.md
              - Add Members: user_guides/projects/project/add_members.md
          - Python:
              - Environments Overview: user_guides/projects/python/python_env_overview.md
              - Clone Environment: user_guides/projects/python/python_env_clone.md
              - Install Library: user_guides/projects/python/python_install.md
              - Export Environment: user_guides/projects/python/python_env_export.md
              - Custom Commands: user_guides/projects/python/custom_commands.md
              - Environment History: user_guides/projects/python/environment_history.md
          - Jupyter:
              - Run Python Notebook: user_guides/projects/jupyter/python_notebook.md
              - Run PySpark Notebook: user_guides/projects/jupyter/spark_notebook.md
              - Run Ray Notebook: user_guides/projects/jupyter/ray_notebook.md
              - Remote Filesystem Driver: user_guides/projects/jupyter/remote_filesystem_driver.md
          - Jobs:
              - Run Python Job: user_guides/projects/jobs/python_job.md
              - Run Jupyter Notebook Job: user_guides/projects/jobs/notebook_job.md
              - Run PySpark Job: user_guides/projects/jobs/pyspark_job.md
              - Run Spark Job: user_guides/projects/jobs/spark_job.md
              - Run Ray Job: user_guides/projects/jobs/ray_job.md
              - Scheduling: user_guides/projects/jobs/schedule_job.md
          - Kubernetes Scheduling:
              - Base: user_guides/projects/scheduling/kube_scheduler.md
              - Kueue: user_guides/projects/scheduling/kueue_details.md

          - Airflow: user_guides/projects/airflow/airflow.md
          - OpenSearch:
              - Connect: user_guides/projects/opensearch/connect.md
              - KNN: user_guides/projects/opensearch/knn.md
          - Kafka:
              - Create Schema: user_guides/projects/kafka/create_schema.md
              - Create Topic: user_guides/projects/kafka/create_topic.md
              - Produce messages: user_guides/projects/kafka/produce_messages.md
              - Consume messages: user_guides/projects/kafka/consume_messages.md
          - Git:
              - Configure Git Provider: user_guides/projects/git/configure_git_provider.md
              - Clone Repository: user_guides/projects/git/clone_repo.md
              - Repository Actions: user_guides/projects/git/repository_actions.md
          - Secrets:
              - Create Secret: user_guides/projects/secrets/create_secret.md
          - Api Keys:
              - Create API Key: user_guides/projects/api_key/create_api_key.md
          - AWS IAM Roles: user_guides/projects/iam_role/iam_role_chaining.md
      - MLOps:
          - user_guides/mlops/index.md
          - Model Registry:
              - user_guides/mlops/registry/index.md
              - Frameworks:
                  - TensorFlow: user_guides/mlops/registry/frameworks/tf.md
                  - Torch: user_guides/mlops/registry/frameworks/tch.md
                  - Scikit-learn: user_guides/mlops/registry/frameworks/skl.md
                  - LLM: user_guides/mlops/registry/frameworks/llm.md
                  - Python: user_guides/mlops/registry/frameworks/python.md
              - Model Schema: user_guides/mlops/registry/model_schema.md
              - Input Example: user_guides/mlops/registry/input_example.md
              - Model Evaluation Images: user_guides/mlops/registry/model_evaluation_images.md
          - Model Serving:
              - user_guides/mlops/serving/index.md
              - Deployment:
                  - Deployment creation: user_guides/mlops/serving/deployment.md
                  - Deployment state: user_guides/mlops/serving/deployment-state.md
              - Predictor: user_guides/mlops/serving/predictor.md
              - Transformer: user_guides/mlops/serving/transformer.md
              - Resource Allocation: user_guides/mlops/serving/resources.md
              - Inference Logger: user_guides/mlops/serving/inference-logger.md
              - Inference Batcher: user_guides/mlops/serving/inference-batcher.md
              - API Protocol: user_guides/mlops/serving/api-protocol.md
              - REST API: user_guides/mlops/serving/rest-api.md
              - Troubleshooting: user_guides/mlops/serving/troubleshooting.md
              - External Access: user_guides/mlops/serving/external-access.md
          - Vector Database: user_guides/fs/vector_similarity_search.md
          - Provenance: user_guides/mlops/provenance/provenance.md
      - Migration:
          - 3.X to 4.0: user_guides/migration/40_migration.md
  - Setup and Administration:
      - setup_installation/index.md
      - Client Installation:
          - user_guides/client_installation/index.md
      - Cloud Installation:
          - AWS - Getting Started: setup_installation/aws/getting_started.md
          - Azure - Getting Started: setup_installation/azure/getting_started.md
          - GCP - Getting Started: setup_installation/gcp/getting_started.md
      - On-Prem:
          - Background: setup_installation/on_prem/contact_hopsworks.md
          - External Kafka cluster: setup_installation/on_prem/external_kafka_cluster.md
      - Administration:
          - Cluster Configuration: setup_installation/admin/variables.md
          - Introduction: setup_installation/admin/index.md
          - User Management: setup_installation/admin/user.md
          - Project Management: setup_installation/admin/project.md
          - Configure Alerts: setup_installation/admin/alert.md
          - IAM Role Chaining: setup_installation/admin/roleChaining.md
          - Configure Project Mapping: setup_installation/admin/configure-project-mapping.md
          - Monitoring:
              - Services Dashboards: setup_installation/admin/monitoring/grafana.md
              - Export metrics: setup_installation/admin/monitoring/export-metrics.md
              - Services Logs: setup_installation/admin/monitoring/services-logs.md
          - Authentication:
              - Configure Authentication: setup_installation/admin/auth.md
              - Configure OAuth2:
                  - Register an Identity Provider: setup_installation/admin/oauth2/create-client.md
                  - Create Okta Client: setup_installation/admin/oauth2/create-okta-client.md
                  - Create Azure Client: setup_installation/admin/oauth2/create-azure-client.md
                  - Configure Project Mapping: setup_installation/admin/oauth2/configure-project-mapping.md
              - Configure LDAP/Kerberos:
                  - Configure LDAP: setup_installation/admin/ldap/configure-ldap.md
                  - Configure Kerberos: setup_installation/admin/ldap/configure-krb.md
                  - Configure server for LDAP and Kerberos: setup_installation/admin/ldap/configure-server.md
                  - Configure Project Mapping: setup_installation/admin/ldap/configure-project-mapping.md
          - High availability / Disaster Recovery:
              - Overview: setup_installation/admin/ha-dr/intro.md
              - High Availability: setup_installation/admin/ha-dr/ha.md
              - Disaster Recovery: setup_installation/admin/ha-dr/dr.md
          - Audit:
              - Access Audit Logs: setup_installation/admin/audit/audit-logs.md
              - Export Audit Logs: setup_installation/admin/audit/export-audit-logs.md
  - Python API: "!import https://github.com/aversey/hopsworks-api?branch=branch-4.7"
  - Java API: javadoc
  - Community ↗: https://community.hopsworks.ai/

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/images/favicon.ico
  logo: assets/images/hops-logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: "Roboto"
    code: "IBM Plex Mono"
  palette:
    - scheme: hopsworks
      media: "(prefers-color-scheme: light)"
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: hopsworks
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes

extra:
  version:
    provider: mike
    default: latest
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hopsworks
    - icon: fontawesome/brands/github
      link: https://github.com/logicalclocks/hopsworks-api
    - icon: fontawesome/brands/discourse
      link: https://community.hopsworks.ai/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/hopsworks/
    - icon: fontawesome/brands/slack
      link: https://bit.ly/publichopsworks
  analytics:
    provider: google
    property: G-64FEEXPSDN

extra_css:
  - css/custom.css
  - css/marctech.css

extra_javascript:
  - js/quickstart-fullscreen.js

plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
  - mkdocs-jupyter
  - macros:
      # have to use custom templating string otherwise it interferes with jupyter notebooks
      j2_block_start_string: "{{{%"
      j2_block_end_string: "%}}}"
      j2_variable_start_string: "{{{"
      j2_variable_end_string: "}}}"
  - mike:
      canonical_version: latest
  - multirepo
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false
            link_source: true
            docstring_section_style: spacy
          inventories:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: "#"
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
