name: mkdocs-main

on:
  push:
    branches: [ main ]

jobs:
  publish-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install doc deps
        run: pip install pip==22.0.3 && pip3 install 'git+https://github.com/logicalclocks/feature-store-api@master#egg=hsfs[docs]&subdirectory=python'

      - name: setup git
        run: |
          git config --global user.name MkDocs
          git config --global user.email mkdocs@docs.hopsworks.ai

      - name: build docs
        run: mkdocs build

      - name: deploy docs
        run: mkdocs gh-deploy

